version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module1:
    image: 11239956/selenium-testng-docker:1.0.9
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result1:/user/share/testngdocker/test-output
  search-module2:
    image: 11239956/selenium-testng-docker:1.0.9
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/user/share/testngdocker/test-output
  book-flight-module1:
    image: 11239956/selenium-testng-docker:1.0.9
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result1:/user/share/testngdocker/test-output
  book-flight-module2:
    image: 11239956/selenium-testng-docker:1.0.9
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result2:/user/share/testngdocker/test-output